In [2]:
import pandas as pd

dfs = {}
df_cp = pd.read_csv(f"best_cp.csv")
df_sa = pd.read_csv(f"best_sa.csv")

In [3]:
df_cp.sort_values(by="Testcase")

,Unnamed: 0,Index,Testcase,Security,Redundancy,Method,# ES,# Switches,# Streams,# Receiver Tasks,...,Infeasible apps,Overlapping number,Stream with overlap,Tstart,alpha,Prmv,k,a,b,w
9,0,0,large2,True,True,CP_ROUTING_CP_SCHEDULING,32,16,37,77,...,0/22,0,0,10,0.999,0.8,5,50000,10000,10
6,0,0,medium1,True,True,CP_ROUTING_CP_SCHEDULING,16,8,23,34,...,0/14,0,0,10,0.999,0.8,5,50000,10000,10
7,0,0,medium2,True,True,CP_ROUTING_CP_SCHEDULING,16,8,30,47,...,0/12,0,0,10,0.999,0.8,5,50000,10000,10
8,0,0,medium3,True,True,CP_ROUTING_CP_SCHEDULING,16,8,36,53,...,0/13,0,0,10,0.999,0.8,5,50000,10000,10
3,0,0,small1,True,True,CP_ROUTING_CP_SCHEDULING,8,4,10,16,...,0/7,0,0,10,0.999,0.8,5,50000,10000,10
4,0,0,small2,True,True,CP_ROUTING_CP_SCHEDULING,8,4,14,20,...,0/10,0,0,10,0.999,0.8,5,50000,10000,10
5,0,0,small3,True,True,CP_ROUTING_CP_SCHEDULING,8,4,29,48,...,0/12,0,0,10,0.999,0.8,5,50000,10000,10
0,0,0,tiny1,True,True,CP_ROUTING_CP_SCHEDULING,4,2,2,2,...,0/4,0,0,10,0.999,0.8,5,50000,10000,10
1,0,0,tiny2,True,True,CP_ROUTING_CP_SCHEDULING,4,2,3,4,...,0/1,0,0,10,0.999,0.8,5,50000,10000,10
2,0,0,tiny3,True,True,CP_ROUTING_CP_SCHEDULING,4,2,11,13,...,0/5,0,0,10,0.999,0.8,5,50000,10000,10

In [11]:
df = df_cp.loc[df_cp["Testcase"] == "giant2"]
df

Empty DataFrame
Columns: [Unnamed: 0, Index, Testcase, Security, Redundancy, Method, # ES, # Switches, # Streams, # Receiver Tasks, # Tasks, Total cost, Routing cost, Scheduling cost, Normal application latency, Infeasible Apps, Bandwidth use (Mean,%), CPU use (Mean,%), Optimization Time (ms), First feasible solution time (ms), Total Runtime (ms), Infeasible apps, Overlapping number, Stream with overlap, Tstart, alpha, Prmv, k, a, b, w]
Index: []

[0 rows x 31 columns]

In [13]:
columns = ["Test case", "Method", "# ES", "# SW", "# Streams", "# Recv. Tasks", "# Tasks", "Cost", "T"]
tc_name = ["tiny1", "tiny2", "tiny3", "small1", "small2", "small3", "medium1", "medium2", "medium3", "large1", "large2", "large3", "huge1", "huge2", "huge3", "giant1", "giant2", "giant3"]
df_result = pd.DataFrame([], columns = columns)

i = 0
for name in tc_name:
    # Parse CP results
    df = df_cp.loc[df_cp["Testcase"] == name]
    if not df.empty:
        method = "CP"
        nr_es = int(df["# ES"])
        nr_sw = int(df["# Switches"])
        nr_s = int(df["# Streams"])
        nr_recv_tasks = int(df["# Receiver Tasks"])
        nr_tasks = int(df["# Tasks"])
        cost = int(df["Total cost"])
        t = int(df["Total Runtime (ms)"])
        df_result.loc[i] = [name, method, nr_es, nr_sw, nr_s, nr_recv_tasks, nr_tasks, cost, t]
    else:
        method = "CP"
        df_result.loc[i] = [name, method, "/", "/", "/", "/" , "/" , "/" , "/"]
        
    # Parse SA results
    df = df_sa.loc[df_sa["Testcase"] == name]
    if not df.empty:
        method = "SA"
        nr_es = int(df["# ES"])
        nr_sw = int(df["# Switches"])
        nr_s = int(df["# Streams"])
        nr_recv_tasks = int(df["# Receiver Tasks"])
        nr_tasks = int(df["# Tasks"])
        cost = int(df["Total cost"])
        t = int(df["Total Runtime (ms)"])
        df_result.loc[i+1] = [name, method, nr_es, nr_sw, nr_s, nr_recv_tasks, nr_tasks, cost, t]
    else:
        method = "SA"
        df_result.loc[i+1] = [name, method, "/", "/", "/", "/" , "/" , "/" , "/"]
    i += 2
df_result

   Test case Method # ES # SW # Streams # Recv. Tasks # Tasks    Cost        T
0      tiny1     CP    4    2         2             2       6    1708      202
1      tiny1     SA    4    2         2             2       6    1708   580060
2      tiny2     CP    4    2         3             4       6    1732      177
3      tiny2     SA    4    2         3             4       6    1732   580041
4      tiny3     CP    4    2        11            13      15    7450   860062
5      tiny3     SA    4    2        11            13      15   18088   580194
6     small1     CP    8    4        10            16      20    5421     2163
7     small1     SA    8    4        10            16      20   13303   580127
8     small2     CP    8    4        14            20      23    9110  3603731
9     small2     SA    8    4        14            20      23   13794   580387
10    small3     CP    8    4        29            48      35    7705  1054492
11    small3     SA    8    4        29            48      35   13781   580348
12   medium1     CP   16    8        23            34      37   12991   269673
13   medium1     SA   16    8        23            34      37   22883   580115
14   medium2     CP   16    8        30            47      43    6552   311792
15   medium2     SA   16    8        30            47      43   19455   580645
16   medium3     CP   16    8        36            53      47   15515  3698295
17   medium3     SA   16    8        36            53      47   26486   580909
18    large1     CP    /    /         /             /       /       /        /
19    large1     SA   32   16        47            86      73   43872   580520
20    large2     CP   32   16        37            77      72   25199  3289327
21    large2     SA   32   16        37            77      72   41071  1781240
22    large3     CP    /    /         /             /       /       /        /
23    large3     SA   32   16        69           170     104   34860   581647
24     huge1     CP    /    /         /             /       /       /        /
25     huge1     SA   64   32        84           183     133   73070   584273
26     huge2     CP    /    /         /             /       /       /        /
27     huge2     SA   64   32        99           213     161   57246   586096
28     huge3     CP    /    /         /             /       /       /        /
29     huge3     SA   64   32        99           197     169   93357   582557
30    giant1     CP    /    /         /             /       /       /        /
31    giant1     SA  128   64       144           347     261  101799  1188149
32    giant2     CP    /    /         /             /       /       /        /
33    giant2     SA  192   96       313           693     516  244823  1248054
34    giant3     CP    /    /         /             /       /       /        /
35    giant3     SA  256  128       600          1264    1028  565472  1431890

In [12]:
df_result.to_csv("impact_results.csv")

In [17]:
df["Bandwidth use (Mean,%)"].mean()

0.062296314285714284